### PR TITLE
Trace file format parser

### PR DESCRIPTION
**Pull request by iitalics**
Don't pull if we want to change the file format, but right now it's pretty simple:
`# comment...`
`module <MODULE>`
`1 <ADDRESS_TO_LOAD>`
`2 <ADDRESS_TO_STORE>`
Step N times before performing access:
`+<N> <TYPE> <ADDRESS>`
By default all accesses are 1 step apart (implicit `+1`)

### CODE REVIEW

**Comment by agostini01** [comment]
Interesting implementation. I like it. Nice use of the "misc" functions. It effective solves the problem for accessing 1 module. 

But, it is not possible to accesses 2 different modules at the same cycle (unless you tag to the other module every time, increasing the size of the trace by a lot), or is it?

I ask this, because it is likely that multiple modules will request accesses at the same cycle often (and because you step ahead and already implemented part of this functionality).

Could you adjust so we have the module number on every line?

`module <MODULE>`
`1 <ADDRESS_TO_LOAD>`
`2 <ADDRESS_TO_STORE>`
`Step N times before performing access:`
`+<N> <MODULE> <TYPE> <ADDRESS> // This would be the optimal order.`
By default all accesses are 1 step apart (implicit +1)

Great job!

**Comment by iitalics** [comment]
Hm I will work something out. How would you feel about special chars for differnet types of access, e.g. `@` for load, `!` for store? Or should I just keep it as `1` and `2`?

**Comment by agostini01** [comment]
1 and 2 is better, as the access function complies with those parameters:

```
            switch (type) {
            case 0:
                the_type = mem::Module::AccessInvalid;
                break;
            case 1:
                the_type = mem::Module::AccessLoad;
                break;
            case 2:
                the_type = mem::Module::AccessStore;
                break;
            case 3:
                the_type = mem::Module::AccessNCStore;
                break;
            default:
                the_type = mem::Module::AccessInvalid;
                break;
            }
```

ps.: I updated the previous comment

**Comment by amirkavyan** [comment]
I now this is closed, by I would suggest introducing a enumeration variable for the type. Enums map the values to different types:
enum AccessType
```
{
        AccessTypeInvalid = 0,
        AccessTypeLoad,
        AccessTypeStore,
        AccessTypeNCStore
}

```
Also I am not a fan of variable **the_type**. It's name should be reflective of its purpose.
Then the code changes to:
```
            switch (type) {
            case AccessTypeLoad:
                the_type = mem::Module::AccessLoad;
                break;
            case AccessTypeStore:
                the_type = mem::Module::AccessStore;
                break;
            case AccessTypeNCStore:
                the_type = mem::Module::AccessNCStore;
                break;
            case AccessTypeInvalid:
            default:
                the_type = mem::Module::AccessInvalid;
                break;
            }
```
Pay attention that I have moved the equivalent of the case zero.

**Pull request closed without merging**
